### ISSUE TITLE
[Feature Request] Provide possibility to copy user-provided environment-variables

### ISSUE THREAD

**Issue by lihue** [bluemixgaragelondon/cf-blue-green-deploy#39]
We store some sensitive data (passwords, access tokents) as environment variables. Since those data is sensitive, we don't have it in the manifest file but on the application instance directly.
It would be great if you can provide a flag that copies all user-provided variables to the new instance.

**Comment by holly-cummins** [comment]
We have a similar requirement, and use user provided services (https://docs.cloudfoundry.org/devguide/services/user-provided.html) to store our sensitive data. For example, we might reference a "supersecret-credentials" service in the manifest.yml, and then create (once) it using 

     cf cups supersecret-credentials -p '{"username":"admin","password":"pa55woRD"}'

That service is then automatically bound to the application, even when blue-green-deploy is used. 

Would this pattern address your requirement, or is there a specific need for environment variable support?

**Comment by lihue** [comment]
Yes, this is a useful solution. Thank you for your feedback.

**Comment by SpencerKaiser** [comment]
So it looks like the newer version of `cups` is `create-user-defined-service` but unfortunately I can't run this from within a GitHub Actions (which I want to use because it allows me to store my credentials in GitHub securely) because it [fails after creating the service the first time](https://github.com/nulldriver/cf-cli-resource/issues/6#issuecomment-671412057).

Am I missing something? I just need a way to securely set environment variables for my service when I deploy.

**Comment by holly-cummins** [comment]
From the linked issue, I think you've worked out that running 'cf uups` in your GitHub action will work for you, is that right?

**Comment by SpencerKaiser** [comment]
Yea it does, but I'd prefer to have something I could run to create it instead of needing to run the creation manually 😓 the shell scripting for that could get messy and it's definitely not my expertise
