### ISSUE TITLE
Create previous app

### ISSUE THREAD

**Issue by eloo** [bluemixgaragelondon/cf-blue-green-deploy#47]
Hi,
it would be great if the blue-green could have an additional step were the old green deployment is only stopped and relabeled to something like "previous".
So in case the new green is broken for example by business logic you could easy switch back to the previous version.
What do you think?

Thanks

**Comment by holly-cummins** [comment]
I think this is already possible, albeit not especially well documented. On a successful push, a myappname-old app is left running (see #29 for discussion of this). 

#7 also covers a more complete version of your requirement, so that you don't need to implement the steps of switching the routes yourself if you want the old version back.

**Comment by Eloo** [comment]
okay. i will try this

**Comment by eloo** [comment]
it seems the plugin is creating and <hostname>-old..
so this can be closed
