### ISSUE TITLE
cf bgd <appName> is not deleting old apps

### ISSUE THREAD

**Issue by naomitayeb** [bluemixgaragelondon/cf-blue-green-deploy#86]
Hi,

After running the command cf bgd <appName>, in my cf space there is still <appName>-old application that is running. it seems that the deletion of old apps step is skipped!
API version:
==========================
cf api                                   1 ↵
api endpoint:   https://api.cf.stagingaws.hanavlab.ondemand.com
api version:    2.134.0
==========================
Any idea what's going on?

Thanks,
Naomi.

**Comment by holly-cummins** [comment]
Hi Naomi, are you using the `--delete-old-apps` command line flag? Could you confirm which version of the plugin you're using?

**Comment by naomitayeb** [comment]
Hi,
No I’ve never used this flag and the issue doesn’t happen. 
I have also specified The API version.

**Comment by holly-cummins** [comment]
Hi Naomi, the version of the CF API isn't going to the same as the version of the blue-green-deploy plugin. However, if you're not using the `--delete-old-apps` option, that explains what you're seeing. This plugin has always left the old apps 'up' by default. We've had some discussions about whether the  default should be to delete, since many users would expect old apps to be deleted by default. However, changing the default is a major change so we're still debating whether the major change is better or worse than the slightly unexpected default. See #29 and #56 for more discussion.

**Comment by naomitayeb** [comment]
Thanks for the explanation, I will add the --delete-old-apps option...
